/**
 * Email template type registry — use with sendTemplateEmail().
 */
export const EMAIL_TYPE = Object.freeze({
  // Account
  EMAIL_VERIFICATION_OTP: "EMAIL_VERIFICATION_OTP",
  WELCOME: "WELCOME",
  ACCOUNT_CREATED: "ACCOUNT_CREATED",
  PASSWORD_RESET: "PASSWORD_RESET",
  LOGIN_CREDENTIALS: "LOGIN_CREDENTIALS",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",

  // Order lifecycle
  ORDER_PLACED: "ORDER_PLACED",
  PAYMENT_SUCCESSFUL: "PAYMENT_SUCCESSFUL",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  ORDER_CONFIRMED: "ORDER_CONFIRMED",
  DESIGN_STARTED: "DESIGN_STARTED",
  DESIGN_APPROVAL_REQUIRED: "DESIGN_APPROVAL_REQUIRED",
  DESIGN_APPROVED: "DESIGN_APPROVED",
  PRINTING_STARTED: "PRINTING_STARTED",
  PRINTING_COMPLETED: "PRINTING_COMPLETED",
  QUALITY_CHECK: "QUALITY_CHECK",
  PACKED: "PACKED",
  SHIPPED: "SHIPPED",
  OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED",
  REFUND_INITIATED: "REFUND_INITIATED",
  REFUND_COMPLETED: "REFUND_COMPLETED",
  ORDER_RETURNED: "ORDER_RETURNED",

  // Enquiry
  ENQUIRY_RECEIVED_ADMIN: "ENQUIRY_RECEIVED_ADMIN",
  ENQUIRY_CONFIRMATION_CUSTOMER: "ENQUIRY_CONFIRMATION_CUSTOMER",

  // Invoice & marketing
  INVOICE: "INVOICE",
  NEWSLETTER: "NEWSLETTER",
  PROMOTIONAL_OFFER: "PROMOTIONAL_OFFER",
  REVIEW_REQUEST: "REVIEW_REQUEST",

  // Admin & system
  CONTACT_FORM_SUBMISSION: "CONTACT_FORM_SUBMISSION",
  ADMIN_NOTIFICATION: "ADMIN_NOTIFICATION",
  LOW_STOCK_ALERT: "LOW_STOCK_ALERT",
});
